name: GitHub Actions Demo
on: [push]
jobs:
  Einit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.17.0]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm install

      - name: build storybook
        run: npm run build:storybook

      - name: e2e test
        run: npm run test:e2e

      - name: lint code
        run: npm run lint
